{% set name = "pydantic-mongo" %}
{% set version = "3.0.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic_mongo-{{ version }}.tar.gz
  sha256: caac6d9a0e1e91a50025e001167511ba5de855c9c290d88eef70fd7336742441

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pymongo >=4.9,<5.0
    - pydantic >=2.0.2,<3.0.0

test:
  source_files:
    - test/
  imports:
    - pydantic_mongo
  commands:
    - pip check
    - pytest ./test -k 'not test_enhance_meta and not test_async_repository'  # [not win]
  requires:
    - pip
    - pytest
    - pymongo <4.11  # https://github.com/mongomock/mongomock/issues/912$0
    - mongomock
    - python {{ python_min }}

about:
  home: https://github.com/jefersondaniel/pydantic-mongo
  summary: Document object mapper for pydantic and pymongo
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jonashaag
