{% set name = "pydantic-mongo" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydantic_mongo-{{ version }}.tar.gz
  sha256: d1b05d6bf28e0eeca66809a99c362b958bf6fc6af59350d44d9a948e5fc30e3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.8
    - pymongo >=4.3,<5.0
    - pydantic >=2.0.2,<3.0.0

test:
  source_files:
    - test/
  imports:
    - pydantic_mongo
  commands:
    - pip check
    - pytest ./test -k 'not test_enhance_meta'  # [not win]
  requires:
    - pip
    - pytest
    - mongomock

about:
  home: https://github.com/jefersondaniel/pydantic-mongo
  summary: Document object mapper for pydantic and pymongo
  license: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - jonashaag
